### ISSUE TITLE
Scanning disabled

### ISSUE THREAD

**Issue by Zyfax** [bayrock/PokeOutlook#1]
I'm getting an error:
Scanning is currently disabled temporarily.
Tryed only pokego-scanner.
$ npm install -g pokego-scanner
$ pokego-scanner --lat=40.4164737 --lng=-3.7042757
Getting same error.

**Comment by bayrock** [comment]
Yeah, I'm going to be replacing the pokego-scanner module in the next commit. However, I corrupted my Visual Studio in the process of reinstalling it. I need it to compile the new scan module, so now I'm stuck in a state of limbo.

Since I know there's some interest in the project I'll try to get this fixed ASAP.

**Comment by Zyfax** [comment]
Great!
It looks nice and clean.
Nice work :+1:

**Comment by Zyfax** [comment]
How is it going?
Still problems with your VS?

**Comment by bayrock** [comment]
Unfortunately Niantic has removed the API that made these services possible.
